### ISSUE TITLE
Missing package gtk-aurora-engine(i686)

### ISSUE THREAD

**Issue by tonyskapunk** [troyengel/scripts#1]
Seems like it was renamed from 'gtk-aurora-engine' to 'gtk-engine-aurora'[1]. Yesterday tried to run archmate.sh failing on that package as unable to find.

**Comment by tonyskapunk** [comment]
[1] https://www.archlinux.org/packages/community/i686/gtk-engine-aurora/

**Comment by troyengel** [comment]
Roger that! I remember seeing this in pacman a few days ago, thanks for the reminder to fix it. :)
